# 允许在铁砧中升级更高等级附魔的列表
enchantments:
    # 附魔的名称 (id应和/enchant指令中的一致, 如: efficiency)
    # 添加一个 "ALL" 来设置除了已经设定以外的所有附魔
    # 警告: 在原版无视等级的附魔 (如: 精准采集、无限）将被本插件无视
    -   name: efficiency
        # 该附魔允许被升级的最大等级
        # 格式:
        # 1. 直接写数字等级(如: 10 -> 允许效率X) 表示允许的最大等级
        # 2. 写拓展的等级(如: "+1" -> 允许效率5+1->VI) 表示在原版最大等级的基础上拓展的等级
        # 你可以删去max-level, 代表不限制最大等级
        # 警告: 原版仅支持至255级附魔
        max-level: 6

        # 在铁砧内附魔该附魔书在原版基础上额外消耗的经验
        # 格式:
        # 1. 直接写数字经验等级(如: 50 -> 消耗50XP) 表示消耗的经验等级，无论附魔等级多少
        # 2. 写增加的经验等级(如: "*50" -> 消耗上一级的经验+50XP) 表示在上一级基础上额外消耗的经验等级
        cost: "*50"

    #-   name: ALL
    #    max-level: "+1"
    #    cost: 100
