name: EnchantBookPlus
version: '${project.version}'
author: Stars
main: cn.stars.enchantbookplus.EnchantBookPlus
description: "允许将附魔书合并至超过原版限制的等级"
api-version: 1.21
softdepend:
  - AnvilUnlocker
commands:
  enchantbookplus:
    description: "EnchantBookPlus 主命令"
    usage: "/<command>"
